#!/bin/bash

# [ "$(stat -c %y ~/.cache/corona 2>/dev/null | cut -d' ' -f1)" != "$(date '+%Y-%m-%d')" ] &&
#     curl https://corona-stats.online/Russia > ~/.cache/corona

curl https://corona-stats.online/Russia > ~/.cache/corona

info=$(grep 'Russia' ~/.cache/corona                        \
     | sed -r "s/\x1B\[([0-9]{1,3}(;[0-9]{1,2})?)?[mGK]//g" \
     | sed 's: ::g'                                         \
     | sed 's:║::g'                                         \
     | sed 's:│:|:g'                                        \
     | cut -d'|' -f3,4,5,6                                  \
     | sed 's:▲::g'                                         \
     | sed 's:,::g') 

russia_infected=$(echo $info | cut -d'|' -f1)
russia_infected_today=$(echo $info | cut -d'|' -f2)
russia_deaths=$(echo $info | cut -d'|' -f3)
russia_deaths_today=$(echo $info | cut -d'|' -f4)

if [ ! -z $russia_infected_today ]; then 
    echo "Russia: $russia_infected☹️ ($russia_infected_today⤴️), $russia_deaths✝️ ($russia_deaths_today⤴️)"
elif [ ! -z $russia_infected ]; then
    echo "Russia: $russia_infected☹️, $russia_deaths✝️"
else
    echo "No internet..."
fi
